### ISSUE TITLE
[Nuke] Not working due to TypeError

### ISSUE THREAD

**Issue by Redcroft** [Psyop/Cryptomatte#123]
Hi,
We have the latest cryptomatte installed for Nuke10.5v4 but are unable to get the node working with the following issue

```
Traceback (most recent call last):
  File "/usr/local/Nuke10.5v4/plugins/nuke/callbacks.py", line 127, in knobChanged
    _doCallbacks(knobChangeds)
  File "/usr/local/Nuke10.5v4/plugins/nuke/callbacks.py", line 46, in _doCallbacks
    f[0](*f[1],**f[2])
  File "/home/redsith/.nuke/cryptomatte_utilities.py", line 42, in <lambda>
    nuke.thisNode(), nuke.thisKnob()), nodeClass='Cryptomatte')
  File "/home/redsith/.nuke/cryptomatte_utilities.py", line 453, in cryptomatte_knob_changed_event
    keyed_object = cinfo.id_to_name(ID_value) or "<%s>" % ID_value
  File "/home/redsith/.nuke/cryptomatte_utilities.py", line 358, in id_to_name
    self.parse_manifest()
  File "/home/redsith/.nuke/cryptomatte_utilities.py", line 323, in parse_manifest
    manifest = self.lazy_load_manifest()
  File "/home/redsith/.nuke/cryptomatte_utilities.py", line 290, in lazy_load_manifest
    return json.loads(self.cryptomattes[self.selection]['manifest'])
  File "/usr/local/Nuke10.5v4/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Nuke10.5v4/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```
Renders are done with the latest 3Delight 1.7.26
Thanks

**Comment by jonahfriedman** [comment]
This sounds like it's the same as #124 (closing as a duplicate). Thanks for the report, please follow that ticket instead.
