### ISSUE TITLE
Errors on script load if gizmo is connected to erroring read node

### ISSUE THREAD

**Issue by jonahfriedman** [Psyop/Cryptomatte#43]
Errors look like so:

```
Traceback (most recent call last):
  File ".../nuke/win64/10.0v6/plugins\nuke\callbacks.py", line 127, in knobChanged
    _doCallbacks(knobChangeds)
  File ".../nuke/win64/10.0v6/plugins\nuke\callbacks.py", line 46, in _doCallbacks
    f[0](*f[1],**f[2])
  File ".../temp/cryptomatte/nuke/cryptomatte_utilities.py", line 40, in <lambda>
    nuke.thisNode(), nuke.thisKnob()), nodeClass='Cryptomatte')
  File ".../temp/cryptomatte/nuke/cryptomatte_utilities.py", line 430, in cryptomatte_knob_changed_event
    _set_keyable_surface_expression(node, cinfo)
  File ".../temp/cryptomatte/nuke/cryptomatte_utilities.py", line 795, in _set_keyable_surface_expression
    for c in cinfo.get_channels():
  File ".../temp/cryptomatte/nuke/cryptomatte_utilities.py", line 214, in get_channels
    return self.cryptomattes[self.selection]["channels"]
KeyError: None
```

(I intend to fix this myself, just adding it here for tracking)

**Comment by jonahfriedman** [comment]
Fixed this in dev.
